
FROM apache/spark:3.5.1

ARG POSTGRESQL_VERSION=42.7.3
ARG HADOOP_AWS_VERSION=3.3.4
ARG AWS_SDK_VERSION=1.12.262
ARG CASSANDRA_CONNECTOR_VERSION=3.4.1
ARG SCALA_VERSION=2.12

USER root

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends wget && \
    rm -rf /var/lib/apt/lists/*


RUN wget -q \
    "https://repo1.maven.org/maven2/org/postgresql/postgresql/${POSTGRESQL_VERSION}/postgresql-${POSTGRESQL_VERSION}.jar" \
    -O /opt/spark/jars/postgresql-${POSTGRESQL_VERSION}.jar

RUN wget -q \
    "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar" \
    -O /opt/spark/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar

RUN wget -q \
    "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar" \
    -O /opt/spark/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar

RUN wget -q \
    "https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector_${SCALA_VERSION}/${CASSANDRA_CONNECTOR_VERSION}/spark-cassandra-connector_${SCALA_VERSION}-${CASSANDRA_CONNECTOR_VERSION}.jar" \
    -O /opt/spark/jars/spark-cassandra-connector_${SCALA_VERSION}-${CASSANDRA_CONNECTOR_VERSION}.jar

RUN wget -q \
    "https://repo1.maven.org/maven2/com/datastax/oss/java-driver-core/4.17.0/java-driver-core-4.17.0.jar" \
    -O /opt/spark/jars/java-driver-core-4.17.0.jar && \
    wget -q \
    "https://repo1.maven.org/maven2/com/datastax/oss/java-driver-query-builder/4.17.0/java-driver-query-builder-4.17.0.jar" \
    -O /opt/spark/jars/java-driver-query-builder-4.17.0.jar && \
    wget -q \
    "https://repo1.maven.org/maven2/com/datastax/oss/native-protocol/1.5.1/native-protocol-1.5.1.jar" \
    -O /opt/spark/jars/native-protocol-1.5.1.jar


RUN echo "=== Installed jars ===" && \
    ls -lh /opt/spark/jars/postgresql-*.jar \
    /opt/spark/jars/hadoop-aws-*.jar \
    /opt/spark/jars/aws-java-sdk-bundle-*.jar \
    /opt/spark/jars/spark-cassandra-connector_*.jar \
    /opt/spark/jars/java-driver-*.jar \
    /opt/spark/jars/native-protocol-*.jar

RUN curl -L -o /opt/spark/jars/cassandra.jar \
    https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector_2.12/3.4.1/spark-cassandra-connector_2.12-3.4.1.jar


USER spark