
FROM apache/airflow:3.2.2

ARG AIRFLOW_VERSION=3.2.2
USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    -r /requirements.txt