
FROM apache/airflow:3.2.2-python3.11

ARG AIRFLOW_VERSION=3.2.2

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    libev4 \
    libev-dev \
    libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
ENV CASS_DRIVER_NO_CYTHON=1

RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-docker \
    -r /requirements.txt